package com.bluefireplatform.entity;

public class IndoorMapmatching {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indoor_mapmatching.trajectory_id
     *
     * @mbggenerated Tue Apr 16 14:59:31 CST 2019
     */
    private Integer trajectoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indoor_mapmatching.user_id
     *
     * @mbggenerated Tue Apr 16 14:59:31 CST 2019
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indoor_mapmatching.start_time
     *
     * @mbggenerated Tue Apr 16 14:59:31 CST 2019
     */
    private String startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indoor_mapmatching.end_time
     *
     * @mbggenerated Tue Apr 16 14:59:31 CST 2019
     */
    private String endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indoor_mapmatching.trajectory_type
     *
     * @mbggenerated Tue Apr 16 14:59:31 CST 2019
     */
    private Integer trajectoryType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indoor_mapmatching.trajectory_src
     *
     * @mbggenerated Tue Apr 16 14:59:31 CST 2019
     */
    private String trajectorySrc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indoor_mapmatching.map_id
     *
     * @mbggenerated Tue Apr 16 14:59:31 CST 2019
     */
    private Integer mapId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indoor_mapmatching.trajectory_id
     *
     * @return the value of indoor_mapmatching.trajectory_id
     *
     * @mbggenerated Tue Apr 16 14:59:31 CST 2019
     */
    public Integer getTrajectoryId() {
        return trajectoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indoor_mapmatching.trajectory_id
     *
     * @param trajectoryId the value for indoor_mapmatching.trajectory_id
     *
     * @mbggenerated Tue Apr 16 14:59:31 CST 2019
     */
    public void setTrajectoryId(Integer trajectoryId) {
        this.trajectoryId = trajectoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indoor_mapmatching.user_id
     *
     * @return the value of indoor_mapmatching.user_id
     *
     * @mbggenerated Tue Apr 16 14:59:31 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indoor_mapmatching.user_id
     *
     * @param userId the value for indoor_mapmatching.user_id
     *
     * @mbggenerated Tue Apr 16 14:59:31 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indoor_mapmatching.start_time
     *
     * @return the value of indoor_mapmatching.start_time
     *
     * @mbggenerated Tue Apr 16 14:59:31 CST 2019
     */
    public String getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indoor_mapmatching.start_time
     *
     * @param startTime the value for indoor_mapmatching.start_time
     *
     * @mbggenerated Tue Apr 16 14:59:31 CST 2019
     */
    public void setStartTime(String startTime) {
        this.startTime = startTime == null ? null : startTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indoor_mapmatching.end_time
     *
     * @return the value of indoor_mapmatching.end_time
     *
     * @mbggenerated Tue Apr 16 14:59:31 CST 2019
     */
    public String getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indoor_mapmatching.end_time
     *
     * @param endTime the value for indoor_mapmatching.end_time
     *
     * @mbggenerated Tue Apr 16 14:59:31 CST 2019
     */
    public void setEndTime(String endTime) {
        this.endTime = endTime == null ? null : endTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indoor_mapmatching.trajectory_type
     *
     * @return the value of indoor_mapmatching.trajectory_type
     *
     * @mbggenerated Tue Apr 16 14:59:31 CST 2019
     */
    public Integer getTrajectoryType() {
        return trajectoryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indoor_mapmatching.trajectory_type
     *
     * @param trajectoryType the value for indoor_mapmatching.trajectory_type
     *
     * @mbggenerated Tue Apr 16 14:59:31 CST 2019
     */
    public void setTrajectoryType(Integer trajectoryType) {
        this.trajectoryType = trajectoryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indoor_mapmatching.trajectory_src
     *
     * @return the value of indoor_mapmatching.trajectory_src
     *
     * @mbggenerated Tue Apr 16 14:59:31 CST 2019
     */
    public String getTrajectorySrc() {
        return trajectorySrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indoor_mapmatching.trajectory_src
     *
     * @param trajectorySrc the value for indoor_mapmatching.trajectory_src
     *
     * @mbggenerated Tue Apr 16 14:59:31 CST 2019
     */
    public void setTrajectorySrc(String trajectorySrc) {
        this.trajectorySrc = trajectorySrc == null ? null : trajectorySrc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indoor_mapmatching.map_id
     *
     * @return the value of indoor_mapmatching.map_id
     *
     * @mbggenerated Tue Apr 16 14:59:31 CST 2019
     */
    public Integer getMapId() {
        return mapId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indoor_mapmatching.map_id
     *
     * @param mapId the value for indoor_mapmatching.map_id
     *
     * @mbggenerated Tue Apr 16 14:59:31 CST 2019
     */
    public void setMapId(Integer mapId) {
        this.mapId = mapId;
    }
}