package com.bluefireplatform.entity;

public class IndoorPresentLocation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indoor_present_location.location_id
     *
     * @mbggenerated Thu May 09 09:23:18 CST 2019
     */
    private Integer locationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indoor_present_location.user_id
     *
     * @mbggenerated Thu May 09 09:23:18 CST 2019
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indoor_present_location.x
     *
     * @mbggenerated Thu May 09 09:23:18 CST 2019
     */
    private Double x;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indoor_present_location.y
     *
     * @mbggenerated Thu May 09 09:23:18 CST 2019
     */
    private Double y;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indoor_present_location.time_stamp
     *
     * @mbggenerated Thu May 09 09:23:18 CST 2019
     */
    private Long timeStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indoor_present_location.location_poi
     *
     * @mbggenerated Thu May 09 09:23:18 CST 2019
     */
    private String locationPoi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indoor_present_location.map_id
     *
     * @mbggenerated Thu May 09 09:23:18 CST 2019
     */
    private Integer mapId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indoor_present_location.location_id
     *
     * @return the value of indoor_present_location.location_id
     *
     * @mbggenerated Thu May 09 09:23:18 CST 2019
     */
    public Integer getLocationId() {
        return locationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indoor_present_location.location_id
     *
     * @param locationId the value for indoor_present_location.location_id
     *
     * @mbggenerated Thu May 09 09:23:18 CST 2019
     */
    public void setLocationId(Integer locationId) {
        this.locationId = locationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indoor_present_location.user_id
     *
     * @return the value of indoor_present_location.user_id
     *
     * @mbggenerated Thu May 09 09:23:18 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indoor_present_location.user_id
     *
     * @param userId the value for indoor_present_location.user_id
     *
     * @mbggenerated Thu May 09 09:23:18 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indoor_present_location.x
     *
     * @return the value of indoor_present_location.x
     *
     * @mbggenerated Thu May 09 09:23:18 CST 2019
     */
    public Double getX() {
        return x;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indoor_present_location.x
     *
     * @param x the value for indoor_present_location.x
     *
     * @mbggenerated Thu May 09 09:23:18 CST 2019
     */
    public void setX(Double x) {
        this.x = x;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indoor_present_location.y
     *
     * @return the value of indoor_present_location.y
     *
     * @mbggenerated Thu May 09 09:23:18 CST 2019
     */
    public Double getY() {
        return y;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indoor_present_location.y
     *
     * @param y the value for indoor_present_location.y
     *
     * @mbggenerated Thu May 09 09:23:18 CST 2019
     */
    public void setY(Double y) {
        this.y = y;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indoor_present_location.time_stamp
     *
     * @return the value of indoor_present_location.time_stamp
     *
     * @mbggenerated Thu May 09 09:23:18 CST 2019
     */
    public Long getTimeStamp() {
        return timeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indoor_present_location.time_stamp
     *
     * @param timeStamp the value for indoor_present_location.time_stamp
     *
     * @mbggenerated Thu May 09 09:23:18 CST 2019
     */
    public void setTimeStamp(Long timeStamp) {
        this.timeStamp = timeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indoor_present_location.location_poi
     *
     * @return the value of indoor_present_location.location_poi
     *
     * @mbggenerated Thu May 09 09:23:18 CST 2019
     */
    public String getLocationPoi() {
        return locationPoi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indoor_present_location.location_poi
     *
     * @param locationPoi the value for indoor_present_location.location_poi
     *
     * @mbggenerated Thu May 09 09:23:18 CST 2019
     */
    public void setLocationPoi(String locationPoi) {
        this.locationPoi = locationPoi == null ? null : locationPoi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indoor_present_location.map_id
     *
     * @return the value of indoor_present_location.map_id
     *
     * @mbggenerated Thu May 09 09:23:18 CST 2019
     */
    public Integer getMapId() {
        return mapId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indoor_present_location.map_id
     *
     * @param mapId the value for indoor_present_location.map_id
     *
     * @mbggenerated Thu May 09 09:23:18 CST 2019
     */
    public void setMapId(Integer mapId) {
        this.mapId = mapId;
    }
}