package com.bluefireplatform.entity;

import java.util.ArrayList;
import java.util.List;

public class IndoorMapmatchingExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table indoor_mapmatching
     *
     * @mbggenerated Tue Apr 16 14:59:31 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table indoor_mapmatching
     *
     * @mbggenerated Tue Apr 16 14:59:31 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table indoor_mapmatching
     *
     * @mbggenerated Tue Apr 16 14:59:31 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indoor_mapmatching
     *
     * @mbggenerated Tue Apr 16 14:59:31 CST 2019
     */
    public IndoorMapmatchingExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indoor_mapmatching
     *
     * @mbggenerated Tue Apr 16 14:59:31 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indoor_mapmatching
     *
     * @mbggenerated Tue Apr 16 14:59:31 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indoor_mapmatching
     *
     * @mbggenerated Tue Apr 16 14:59:31 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indoor_mapmatching
     *
     * @mbggenerated Tue Apr 16 14:59:31 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indoor_mapmatching
     *
     * @mbggenerated Tue Apr 16 14:59:31 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indoor_mapmatching
     *
     * @mbggenerated Tue Apr 16 14:59:31 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indoor_mapmatching
     *
     * @mbggenerated Tue Apr 16 14:59:31 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indoor_mapmatching
     *
     * @mbggenerated Tue Apr 16 14:59:31 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indoor_mapmatching
     *
     * @mbggenerated Tue Apr 16 14:59:31 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indoor_mapmatching
     *
     * @mbggenerated Tue Apr 16 14:59:31 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table indoor_mapmatching
     *
     * @mbggenerated Tue Apr 16 14:59:31 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTrajectoryIdIsNull() {
            addCriterion("trajectory_id is null");
            return (Criteria) this;
        }

        public Criteria andTrajectoryIdIsNotNull() {
            addCriterion("trajectory_id is not null");
            return (Criteria) this;
        }

        public Criteria andTrajectoryIdEqualTo(Integer value) {
            addCriterion("trajectory_id =", value, "trajectoryId");
            return (Criteria) this;
        }

        public Criteria andTrajectoryIdNotEqualTo(Integer value) {
            addCriterion("trajectory_id <>", value, "trajectoryId");
            return (Criteria) this;
        }

        public Criteria andTrajectoryIdGreaterThan(Integer value) {
            addCriterion("trajectory_id >", value, "trajectoryId");
            return (Criteria) this;
        }

        public Criteria andTrajectoryIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("trajectory_id >=", value, "trajectoryId");
            return (Criteria) this;
        }

        public Criteria andTrajectoryIdLessThan(Integer value) {
            addCriterion("trajectory_id <", value, "trajectoryId");
            return (Criteria) this;
        }

        public Criteria andTrajectoryIdLessThanOrEqualTo(Integer value) {
            addCriterion("trajectory_id <=", value, "trajectoryId");
            return (Criteria) this;
        }

        public Criteria andTrajectoryIdIn(List<Integer> values) {
            addCriterion("trajectory_id in", values, "trajectoryId");
            return (Criteria) this;
        }

        public Criteria andTrajectoryIdNotIn(List<Integer> values) {
            addCriterion("trajectory_id not in", values, "trajectoryId");
            return (Criteria) this;
        }

        public Criteria andTrajectoryIdBetween(Integer value1, Integer value2) {
            addCriterion("trajectory_id between", value1, value2, "trajectoryId");
            return (Criteria) this;
        }

        public Criteria andTrajectoryIdNotBetween(Integer value1, Integer value2) {
            addCriterion("trajectory_id not between", value1, value2, "trajectoryId");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNull() {
            addCriterion("start_time is null");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNotNull() {
            addCriterion("start_time is not null");
            return (Criteria) this;
        }

        public Criteria andStartTimeEqualTo(String value) {
            addCriterion("start_time =", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotEqualTo(String value) {
            addCriterion("start_time <>", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThan(String value) {
            addCriterion("start_time >", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThanOrEqualTo(String value) {
            addCriterion("start_time >=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThan(String value) {
            addCriterion("start_time <", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThanOrEqualTo(String value) {
            addCriterion("start_time <=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLike(String value) {
            addCriterion("start_time like", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotLike(String value) {
            addCriterion("start_time not like", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeIn(List<String> values) {
            addCriterion("start_time in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotIn(List<String> values) {
            addCriterion("start_time not in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeBetween(String value1, String value2) {
            addCriterion("start_time between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotBetween(String value1, String value2) {
            addCriterion("start_time not between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNull() {
            addCriterion("end_time is null");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNotNull() {
            addCriterion("end_time is not null");
            return (Criteria) this;
        }

        public Criteria andEndTimeEqualTo(String value) {
            addCriterion("end_time =", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotEqualTo(String value) {
            addCriterion("end_time <>", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThan(String value) {
            addCriterion("end_time >", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThanOrEqualTo(String value) {
            addCriterion("end_time >=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThan(String value) {
            addCriterion("end_time <", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThanOrEqualTo(String value) {
            addCriterion("end_time <=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLike(String value) {
            addCriterion("end_time like", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotLike(String value) {
            addCriterion("end_time not like", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIn(List<String> values) {
            addCriterion("end_time in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotIn(List<String> values) {
            addCriterion("end_time not in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeBetween(String value1, String value2) {
            addCriterion("end_time between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotBetween(String value1, String value2) {
            addCriterion("end_time not between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andTrajectoryTypeIsNull() {
            addCriterion("trajectory_type is null");
            return (Criteria) this;
        }

        public Criteria andTrajectoryTypeIsNotNull() {
            addCriterion("trajectory_type is not null");
            return (Criteria) this;
        }

        public Criteria andTrajectoryTypeEqualTo(Integer value) {
            addCriterion("trajectory_type =", value, "trajectoryType");
            return (Criteria) this;
        }

        public Criteria andTrajectoryTypeNotEqualTo(Integer value) {
            addCriterion("trajectory_type <>", value, "trajectoryType");
            return (Criteria) this;
        }

        public Criteria andTrajectoryTypeGreaterThan(Integer value) {
            addCriterion("trajectory_type >", value, "trajectoryType");
            return (Criteria) this;
        }

        public Criteria andTrajectoryTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("trajectory_type >=", value, "trajectoryType");
            return (Criteria) this;
        }

        public Criteria andTrajectoryTypeLessThan(Integer value) {
            addCriterion("trajectory_type <", value, "trajectoryType");
            return (Criteria) this;
        }

        public Criteria andTrajectoryTypeLessThanOrEqualTo(Integer value) {
            addCriterion("trajectory_type <=", value, "trajectoryType");
            return (Criteria) this;
        }

        public Criteria andTrajectoryTypeIn(List<Integer> values) {
            addCriterion("trajectory_type in", values, "trajectoryType");
            return (Criteria) this;
        }

        public Criteria andTrajectoryTypeNotIn(List<Integer> values) {
            addCriterion("trajectory_type not in", values, "trajectoryType");
            return (Criteria) this;
        }

        public Criteria andTrajectoryTypeBetween(Integer value1, Integer value2) {
            addCriterion("trajectory_type between", value1, value2, "trajectoryType");
            return (Criteria) this;
        }

        public Criteria andTrajectoryTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("trajectory_type not between", value1, value2, "trajectoryType");
            return (Criteria) this;
        }

        public Criteria andTrajectorySrcIsNull() {
            addCriterion("trajectory_src is null");
            return (Criteria) this;
        }

        public Criteria andTrajectorySrcIsNotNull() {
            addCriterion("trajectory_src is not null");
            return (Criteria) this;
        }

        public Criteria andTrajectorySrcEqualTo(String value) {
            addCriterion("trajectory_src =", value, "trajectorySrc");
            return (Criteria) this;
        }

        public Criteria andTrajectorySrcNotEqualTo(String value) {
            addCriterion("trajectory_src <>", value, "trajectorySrc");
            return (Criteria) this;
        }

        public Criteria andTrajectorySrcGreaterThan(String value) {
            addCriterion("trajectory_src >", value, "trajectorySrc");
            return (Criteria) this;
        }

        public Criteria andTrajectorySrcGreaterThanOrEqualTo(String value) {
            addCriterion("trajectory_src >=", value, "trajectorySrc");
            return (Criteria) this;
        }

        public Criteria andTrajectorySrcLessThan(String value) {
            addCriterion("trajectory_src <", value, "trajectorySrc");
            return (Criteria) this;
        }

        public Criteria andTrajectorySrcLessThanOrEqualTo(String value) {
            addCriterion("trajectory_src <=", value, "trajectorySrc");
            return (Criteria) this;
        }

        public Criteria andTrajectorySrcLike(String value) {
            addCriterion("trajectory_src like", value, "trajectorySrc");
            return (Criteria) this;
        }

        public Criteria andTrajectorySrcNotLike(String value) {
            addCriterion("trajectory_src not like", value, "trajectorySrc");
            return (Criteria) this;
        }

        public Criteria andTrajectorySrcIn(List<String> values) {
            addCriterion("trajectory_src in", values, "trajectorySrc");
            return (Criteria) this;
        }

        public Criteria andTrajectorySrcNotIn(List<String> values) {
            addCriterion("trajectory_src not in", values, "trajectorySrc");
            return (Criteria) this;
        }

        public Criteria andTrajectorySrcBetween(String value1, String value2) {
            addCriterion("trajectory_src between", value1, value2, "trajectorySrc");
            return (Criteria) this;
        }

        public Criteria andTrajectorySrcNotBetween(String value1, String value2) {
            addCriterion("trajectory_src not between", value1, value2, "trajectorySrc");
            return (Criteria) this;
        }

        public Criteria andMapIdIsNull() {
            addCriterion("map_id is null");
            return (Criteria) this;
        }

        public Criteria andMapIdIsNotNull() {
            addCriterion("map_id is not null");
            return (Criteria) this;
        }

        public Criteria andMapIdEqualTo(Integer value) {
            addCriterion("map_id =", value, "mapId");
            return (Criteria) this;
        }

        public Criteria andMapIdNotEqualTo(Integer value) {
            addCriterion("map_id <>", value, "mapId");
            return (Criteria) this;
        }

        public Criteria andMapIdGreaterThan(Integer value) {
            addCriterion("map_id >", value, "mapId");
            return (Criteria) this;
        }

        public Criteria andMapIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("map_id >=", value, "mapId");
            return (Criteria) this;
        }

        public Criteria andMapIdLessThan(Integer value) {
            addCriterion("map_id <", value, "mapId");
            return (Criteria) this;
        }

        public Criteria andMapIdLessThanOrEqualTo(Integer value) {
            addCriterion("map_id <=", value, "mapId");
            return (Criteria) this;
        }

        public Criteria andMapIdIn(List<Integer> values) {
            addCriterion("map_id in", values, "mapId");
            return (Criteria) this;
        }

        public Criteria andMapIdNotIn(List<Integer> values) {
            addCriterion("map_id not in", values, "mapId");
            return (Criteria) this;
        }

        public Criteria andMapIdBetween(Integer value1, Integer value2) {
            addCriterion("map_id between", value1, value2, "mapId");
            return (Criteria) this;
        }

        public Criteria andMapIdNotBetween(Integer value1, Integer value2) {
            addCriterion("map_id not between", value1, value2, "mapId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table indoor_mapmatching
     *
     * @mbggenerated do_not_delete_during_merge Tue Apr 16 14:59:31 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table indoor_mapmatching
     *
     * @mbggenerated Tue Apr 16 14:59:31 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}