package com.bluefireplatform.entity;

public class IndoorMiddleTab {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indoor_middle_tab.indoor_middle_id
     *
     * @mbggenerated Tue Apr 16 14:59:31 CST 2019
     */
    private Integer indoorMiddleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indoor_middle_tab.original_id
     *
     * @mbggenerated Tue Apr 16 14:59:31 CST 2019
     */
    private Integer originalId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indoor_middle_tab.present_id
     *
     * @mbggenerated Tue Apr 16 14:59:31 CST 2019
     */
    private Integer presentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indoor_middle_tab.present_type
     *
     * @mbggenerated Tue Apr 16 14:59:31 CST 2019
     */
    private Integer presentType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indoor_middle_tab.indoor_middle_id
     *
     * @return the value of indoor_middle_tab.indoor_middle_id
     *
     * @mbggenerated Tue Apr 16 14:59:31 CST 2019
     */
    public Integer getIndoorMiddleId() {
        return indoorMiddleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indoor_middle_tab.indoor_middle_id
     *
     * @param indoorMiddleId the value for indoor_middle_tab.indoor_middle_id
     *
     * @mbggenerated Tue Apr 16 14:59:31 CST 2019
     */
    public void setIndoorMiddleId(Integer indoorMiddleId) {
        this.indoorMiddleId = indoorMiddleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indoor_middle_tab.original_id
     *
     * @return the value of indoor_middle_tab.original_id
     *
     * @mbggenerated Tue Apr 16 14:59:31 CST 2019
     */
    public Integer getOriginalId() {
        return originalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indoor_middle_tab.original_id
     *
     * @param originalId the value for indoor_middle_tab.original_id
     *
     * @mbggenerated Tue Apr 16 14:59:31 CST 2019
     */
    public void setOriginalId(Integer originalId) {
        this.originalId = originalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indoor_middle_tab.present_id
     *
     * @return the value of indoor_middle_tab.present_id
     *
     * @mbggenerated Tue Apr 16 14:59:31 CST 2019
     */
    public Integer getPresentId() {
        return presentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indoor_middle_tab.present_id
     *
     * @param presentId the value for indoor_middle_tab.present_id
     *
     * @mbggenerated Tue Apr 16 14:59:31 CST 2019
     */
    public void setPresentId(Integer presentId) {
        this.presentId = presentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indoor_middle_tab.present_type
     *
     * @return the value of indoor_middle_tab.present_type
     *
     * @mbggenerated Tue Apr 16 14:59:31 CST 2019
     */
    public Integer getPresentType() {
        return presentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indoor_middle_tab.present_type
     *
     * @param presentType the value for indoor_middle_tab.present_type
     *
     * @mbggenerated Tue Apr 16 14:59:31 CST 2019
     */
    public void setPresentType(Integer presentType) {
        this.presentType = presentType;
    }
}