package com.bluefireplatform.entity;

public class Map {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column map.map_id
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    private Integer mapId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column map.map_name
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    private String mapName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column map.map_src
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    private String mapSrc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column map.indoor_mark
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    private Boolean indoorMark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column map.map_id
     *
     * @return the value of map.map_id
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    public Integer getMapId() {
        return mapId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column map.map_id
     *
     * @param mapId the value for map.map_id
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    public void setMapId(Integer mapId) {
        this.mapId = mapId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column map.map_name
     *
     * @return the value of map.map_name
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    public String getMapName() {
        return mapName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column map.map_name
     *
     * @param mapName the value for map.map_name
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    public void setMapName(String mapName) {
        this.mapName = mapName == null ? null : mapName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column map.map_src
     *
     * @return the value of map.map_src
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    public String getMapSrc() {
        return mapSrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column map.map_src
     *
     * @param mapSrc the value for map.map_src
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    public void setMapSrc(String mapSrc) {
        this.mapSrc = mapSrc == null ? null : mapSrc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column map.indoor_mark
     *
     * @return the value of map.indoor_mark
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    public Boolean getIndoorMark() {
        return indoorMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column map.indoor_mark
     *
     * @param indoorMark the value for map.indoor_mark
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    public void setIndoorMark(Boolean indoorMark) {
        this.indoorMark = indoorMark;
    }
}