package com.bluefireplatform.entity;

import java.util.ArrayList;
import java.util.List;

public class MapExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table map
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table map
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table map
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    public MapExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table map
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMapIdIsNull() {
            addCriterion("map_id is null");
            return (Criteria) this;
        }

        public Criteria andMapIdIsNotNull() {
            addCriterion("map_id is not null");
            return (Criteria) this;
        }

        public Criteria andMapIdEqualTo(Integer value) {
            addCriterion("map_id =", value, "mapId");
            return (Criteria) this;
        }

        public Criteria andMapIdNotEqualTo(Integer value) {
            addCriterion("map_id <>", value, "mapId");
            return (Criteria) this;
        }

        public Criteria andMapIdGreaterThan(Integer value) {
            addCriterion("map_id >", value, "mapId");
            return (Criteria) this;
        }

        public Criteria andMapIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("map_id >=", value, "mapId");
            return (Criteria) this;
        }

        public Criteria andMapIdLessThan(Integer value) {
            addCriterion("map_id <", value, "mapId");
            return (Criteria) this;
        }

        public Criteria andMapIdLessThanOrEqualTo(Integer value) {
            addCriterion("map_id <=", value, "mapId");
            return (Criteria) this;
        }

        public Criteria andMapIdIn(List<Integer> values) {
            addCriterion("map_id in", values, "mapId");
            return (Criteria) this;
        }

        public Criteria andMapIdNotIn(List<Integer> values) {
            addCriterion("map_id not in", values, "mapId");
            return (Criteria) this;
        }

        public Criteria andMapIdBetween(Integer value1, Integer value2) {
            addCriterion("map_id between", value1, value2, "mapId");
            return (Criteria) this;
        }

        public Criteria andMapIdNotBetween(Integer value1, Integer value2) {
            addCriterion("map_id not between", value1, value2, "mapId");
            return (Criteria) this;
        }

        public Criteria andMapNameIsNull() {
            addCriterion("map_name is null");
            return (Criteria) this;
        }

        public Criteria andMapNameIsNotNull() {
            addCriterion("map_name is not null");
            return (Criteria) this;
        }

        public Criteria andMapNameEqualTo(String value) {
            addCriterion("map_name =", value, "mapName");
            return (Criteria) this;
        }

        public Criteria andMapNameNotEqualTo(String value) {
            addCriterion("map_name <>", value, "mapName");
            return (Criteria) this;
        }

        public Criteria andMapNameGreaterThan(String value) {
            addCriterion("map_name >", value, "mapName");
            return (Criteria) this;
        }

        public Criteria andMapNameGreaterThanOrEqualTo(String value) {
            addCriterion("map_name >=", value, "mapName");
            return (Criteria) this;
        }

        public Criteria andMapNameLessThan(String value) {
            addCriterion("map_name <", value, "mapName");
            return (Criteria) this;
        }

        public Criteria andMapNameLessThanOrEqualTo(String value) {
            addCriterion("map_name <=", value, "mapName");
            return (Criteria) this;
        }

        public Criteria andMapNameLike(String value) {
            addCriterion("map_name like", value, "mapName");
            return (Criteria) this;
        }

        public Criteria andMapNameNotLike(String value) {
            addCriterion("map_name not like", value, "mapName");
            return (Criteria) this;
        }

        public Criteria andMapNameIn(List<String> values) {
            addCriterion("map_name in", values, "mapName");
            return (Criteria) this;
        }

        public Criteria andMapNameNotIn(List<String> values) {
            addCriterion("map_name not in", values, "mapName");
            return (Criteria) this;
        }

        public Criteria andMapNameBetween(String value1, String value2) {
            addCriterion("map_name between", value1, value2, "mapName");
            return (Criteria) this;
        }

        public Criteria andMapNameNotBetween(String value1, String value2) {
            addCriterion("map_name not between", value1, value2, "mapName");
            return (Criteria) this;
        }

        public Criteria andMapSrcIsNull() {
            addCriterion("map_src is null");
            return (Criteria) this;
        }

        public Criteria andMapSrcIsNotNull() {
            addCriterion("map_src is not null");
            return (Criteria) this;
        }

        public Criteria andMapSrcEqualTo(String value) {
            addCriterion("map_src =", value, "mapSrc");
            return (Criteria) this;
        }

        public Criteria andMapSrcNotEqualTo(String value) {
            addCriterion("map_src <>", value, "mapSrc");
            return (Criteria) this;
        }

        public Criteria andMapSrcGreaterThan(String value) {
            addCriterion("map_src >", value, "mapSrc");
            return (Criteria) this;
        }

        public Criteria andMapSrcGreaterThanOrEqualTo(String value) {
            addCriterion("map_src >=", value, "mapSrc");
            return (Criteria) this;
        }

        public Criteria andMapSrcLessThan(String value) {
            addCriterion("map_src <", value, "mapSrc");
            return (Criteria) this;
        }

        public Criteria andMapSrcLessThanOrEqualTo(String value) {
            addCriterion("map_src <=", value, "mapSrc");
            return (Criteria) this;
        }

        public Criteria andMapSrcLike(String value) {
            addCriterion("map_src like", value, "mapSrc");
            return (Criteria) this;
        }

        public Criteria andMapSrcNotLike(String value) {
            addCriterion("map_src not like", value, "mapSrc");
            return (Criteria) this;
        }

        public Criteria andMapSrcIn(List<String> values) {
            addCriterion("map_src in", values, "mapSrc");
            return (Criteria) this;
        }

        public Criteria andMapSrcNotIn(List<String> values) {
            addCriterion("map_src not in", values, "mapSrc");
            return (Criteria) this;
        }

        public Criteria andMapSrcBetween(String value1, String value2) {
            addCriterion("map_src between", value1, value2, "mapSrc");
            return (Criteria) this;
        }

        public Criteria andMapSrcNotBetween(String value1, String value2) {
            addCriterion("map_src not between", value1, value2, "mapSrc");
            return (Criteria) this;
        }

        public Criteria andIndoorMarkIsNull() {
            addCriterion("indoor_mark is null");
            return (Criteria) this;
        }

        public Criteria andIndoorMarkIsNotNull() {
            addCriterion("indoor_mark is not null");
            return (Criteria) this;
        }

        public Criteria andIndoorMarkEqualTo(Boolean value) {
            addCriterion("indoor_mark =", value, "indoorMark");
            return (Criteria) this;
        }

        public Criteria andIndoorMarkNotEqualTo(Boolean value) {
            addCriterion("indoor_mark <>", value, "indoorMark");
            return (Criteria) this;
        }

        public Criteria andIndoorMarkGreaterThan(Boolean value) {
            addCriterion("indoor_mark >", value, "indoorMark");
            return (Criteria) this;
        }

        public Criteria andIndoorMarkGreaterThanOrEqualTo(Boolean value) {
            addCriterion("indoor_mark >=", value, "indoorMark");
            return (Criteria) this;
        }

        public Criteria andIndoorMarkLessThan(Boolean value) {
            addCriterion("indoor_mark <", value, "indoorMark");
            return (Criteria) this;
        }

        public Criteria andIndoorMarkLessThanOrEqualTo(Boolean value) {
            addCriterion("indoor_mark <=", value, "indoorMark");
            return (Criteria) this;
        }

        public Criteria andIndoorMarkIn(List<Boolean> values) {
            addCriterion("indoor_mark in", values, "indoorMark");
            return (Criteria) this;
        }

        public Criteria andIndoorMarkNotIn(List<Boolean> values) {
            addCriterion("indoor_mark not in", values, "indoorMark");
            return (Criteria) this;
        }

        public Criteria andIndoorMarkBetween(Boolean value1, Boolean value2) {
            addCriterion("indoor_mark between", value1, value2, "indoorMark");
            return (Criteria) this;
        }

        public Criteria andIndoorMarkNotBetween(Boolean value1, Boolean value2) {
            addCriterion("indoor_mark not between", value1, value2, "indoorMark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table map
     *
     * @mbggenerated do_not_delete_during_merge Wed Apr 10 10:47:33 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table map
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}