package com.bluefireplatform.entity;

public class OutdoorPresentLocation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outdoor_present_location.location_id
     *
     * @mbggenerated Wed May 08 15:32:34 CST 2019
     */
    private Integer locationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outdoor_present_location.user_id
     *
     * @mbggenerated Wed May 08 15:32:34 CST 2019
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outdoor_present_location.longitude
     *
     * @mbggenerated Wed May 08 15:32:34 CST 2019
     */
    private Double longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outdoor_present_location.latitude
     *
     * @mbggenerated Wed May 08 15:32:34 CST 2019
     */
    private Double latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outdoor_present_location.time_stamp
     *
     * @mbggenerated Wed May 08 15:32:34 CST 2019
     */
    private Long timeStamp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outdoor_present_location.location_id
     *
     * @return the value of outdoor_present_location.location_id
     *
     * @mbggenerated Wed May 08 15:32:34 CST 2019
     */
    public Integer getLocationId() {
        return locationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outdoor_present_location.location_id
     *
     * @param locationId the value for outdoor_present_location.location_id
     *
     * @mbggenerated Wed May 08 15:32:34 CST 2019
     */
    public void setLocationId(Integer locationId) {
        this.locationId = locationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outdoor_present_location.user_id
     *
     * @return the value of outdoor_present_location.user_id
     *
     * @mbggenerated Wed May 08 15:32:34 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outdoor_present_location.user_id
     *
     * @param userId the value for outdoor_present_location.user_id
     *
     * @mbggenerated Wed May 08 15:32:34 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outdoor_present_location.longitude
     *
     * @return the value of outdoor_present_location.longitude
     *
     * @mbggenerated Wed May 08 15:32:34 CST 2019
     */
    public Double getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outdoor_present_location.longitude
     *
     * @param longitude the value for outdoor_present_location.longitude
     *
     * @mbggenerated Wed May 08 15:32:34 CST 2019
     */
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outdoor_present_location.latitude
     *
     * @return the value of outdoor_present_location.latitude
     *
     * @mbggenerated Wed May 08 15:32:34 CST 2019
     */
    public Double getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outdoor_present_location.latitude
     *
     * @param latitude the value for outdoor_present_location.latitude
     *
     * @mbggenerated Wed May 08 15:32:34 CST 2019
     */
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outdoor_present_location.time_stamp
     *
     * @return the value of outdoor_present_location.time_stamp
     *
     * @mbggenerated Wed May 08 15:32:34 CST 2019
     */
    public Long getTimeStamp() {
        return timeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outdoor_present_location.time_stamp
     *
     * @param timeStamp the value for outdoor_present_location.time_stamp
     *
     * @mbggenerated Wed May 08 15:32:34 CST 2019
     */
    public void setTimeStamp(Long timeStamp) {
        this.timeStamp = timeStamp;
    }
}