package com.bluefireplatform.entity;

public class OutdoorMiddleTab {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outdoor_middle_tab.outdoor_middle_id
     *
     * @mbggenerated Mon Apr 22 14:24:57 CST 2019
     */
    private Integer outdoorMiddleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outdoor_middle_tab.original_id
     *
     * @mbggenerated Mon Apr 22 14:24:57 CST 2019
     */
    private Integer originalId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outdoor_middle_tab.present_id
     *
     * @mbggenerated Mon Apr 22 14:24:57 CST 2019
     */
    private Integer presentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outdoor_middle_tab.present_type
     *
     * @mbggenerated Mon Apr 22 14:24:57 CST 2019
     */
    private Integer presentType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outdoor_middle_tab.outdoor_middle_id
     *
     * @return the value of outdoor_middle_tab.outdoor_middle_id
     *
     * @mbggenerated Mon Apr 22 14:24:57 CST 2019
     */
    public Integer getOutdoorMiddleId() {
        return outdoorMiddleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outdoor_middle_tab.outdoor_middle_id
     *
     * @param outdoorMiddleId the value for outdoor_middle_tab.outdoor_middle_id
     *
     * @mbggenerated Mon Apr 22 14:24:57 CST 2019
     */
    public void setOutdoorMiddleId(Integer outdoorMiddleId) {
        this.outdoorMiddleId = outdoorMiddleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outdoor_middle_tab.original_id
     *
     * @return the value of outdoor_middle_tab.original_id
     *
     * @mbggenerated Mon Apr 22 14:24:57 CST 2019
     */
    public Integer getOriginalId() {
        return originalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outdoor_middle_tab.original_id
     *
     * @param originalId the value for outdoor_middle_tab.original_id
     *
     * @mbggenerated Mon Apr 22 14:24:57 CST 2019
     */
    public void setOriginalId(Integer originalId) {
        this.originalId = originalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outdoor_middle_tab.present_id
     *
     * @return the value of outdoor_middle_tab.present_id
     *
     * @mbggenerated Mon Apr 22 14:24:57 CST 2019
     */
    public Integer getPresentId() {
        return presentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outdoor_middle_tab.present_id
     *
     * @param presentId the value for outdoor_middle_tab.present_id
     *
     * @mbggenerated Mon Apr 22 14:24:57 CST 2019
     */
    public void setPresentId(Integer presentId) {
        this.presentId = presentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outdoor_middle_tab.present_type
     *
     * @return the value of outdoor_middle_tab.present_type
     *
     * @mbggenerated Mon Apr 22 14:24:57 CST 2019
     */
    public Integer getPresentType() {
        return presentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outdoor_middle_tab.present_type
     *
     * @param presentType the value for outdoor_middle_tab.present_type
     *
     * @mbggenerated Mon Apr 22 14:24:57 CST 2019
     */
    public void setPresentType(Integer presentType) {
        this.presentType = presentType;
    }
}