package com.bluefireplatform.entity;

public class Poi {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poi.poi_id
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    private Integer poiId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poi.map_id
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    private Integer mapId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poi.poi_name
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    private String poiName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poi.poi_vertex
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    private String poiVertex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poi.poi_center
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    private String poiCenter;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poi.poi_id
     *
     * @return the value of poi.poi_id
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    public Integer getPoiId() {
        return poiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poi.poi_id
     *
     * @param poiId the value for poi.poi_id
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    public void setPoiId(Integer poiId) {
        this.poiId = poiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poi.map_id
     *
     * @return the value of poi.map_id
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    public Integer getMapId() {
        return mapId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poi.map_id
     *
     * @param mapId the value for poi.map_id
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    public void setMapId(Integer mapId) {
        this.mapId = mapId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poi.poi_name
     *
     * @return the value of poi.poi_name
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    public String getPoiName() {
        return poiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poi.poi_name
     *
     * @param poiName the value for poi.poi_name
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    public void setPoiName(String poiName) {
        this.poiName = poiName == null ? null : poiName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poi.poi_vertex
     *
     * @return the value of poi.poi_vertex
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    public String getPoiVertex() {
        return poiVertex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poi.poi_vertex
     *
     * @param poiVertex the value for poi.poi_vertex
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    public void setPoiVertex(String poiVertex) {
        this.poiVertex = poiVertex == null ? null : poiVertex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poi.poi_center
     *
     * @return the value of poi.poi_center
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    public String getPoiCenter() {
        return poiCenter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poi.poi_center
     *
     * @param poiCenter the value for poi.poi_center
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    public void setPoiCenter(String poiCenter) {
        this.poiCenter = poiCenter == null ? null : poiCenter.trim();
    }
}