package com.bluefireplatform.entity;

import java.util.ArrayList;
import java.util.List;

public class PoiExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table poi
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table poi
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table poi
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poi
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    public PoiExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poi
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poi
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poi
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poi
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poi
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poi
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poi
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poi
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poi
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poi
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table poi
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPoiIdIsNull() {
            addCriterion("poi_id is null");
            return (Criteria) this;
        }

        public Criteria andPoiIdIsNotNull() {
            addCriterion("poi_id is not null");
            return (Criteria) this;
        }

        public Criteria andPoiIdEqualTo(Integer value) {
            addCriterion("poi_id =", value, "poiId");
            return (Criteria) this;
        }

        public Criteria andPoiIdNotEqualTo(Integer value) {
            addCriterion("poi_id <>", value, "poiId");
            return (Criteria) this;
        }

        public Criteria andPoiIdGreaterThan(Integer value) {
            addCriterion("poi_id >", value, "poiId");
            return (Criteria) this;
        }

        public Criteria andPoiIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("poi_id >=", value, "poiId");
            return (Criteria) this;
        }

        public Criteria andPoiIdLessThan(Integer value) {
            addCriterion("poi_id <", value, "poiId");
            return (Criteria) this;
        }

        public Criteria andPoiIdLessThanOrEqualTo(Integer value) {
            addCriterion("poi_id <=", value, "poiId");
            return (Criteria) this;
        }

        public Criteria andPoiIdIn(List<Integer> values) {
            addCriterion("poi_id in", values, "poiId");
            return (Criteria) this;
        }

        public Criteria andPoiIdNotIn(List<Integer> values) {
            addCriterion("poi_id not in", values, "poiId");
            return (Criteria) this;
        }

        public Criteria andPoiIdBetween(Integer value1, Integer value2) {
            addCriterion("poi_id between", value1, value2, "poiId");
            return (Criteria) this;
        }

        public Criteria andPoiIdNotBetween(Integer value1, Integer value2) {
            addCriterion("poi_id not between", value1, value2, "poiId");
            return (Criteria) this;
        }

        public Criteria andMapIdIsNull() {
            addCriterion("map_id is null");
            return (Criteria) this;
        }

        public Criteria andMapIdIsNotNull() {
            addCriterion("map_id is not null");
            return (Criteria) this;
        }

        public Criteria andMapIdEqualTo(Integer value) {
            addCriterion("map_id =", value, "mapId");
            return (Criteria) this;
        }

        public Criteria andMapIdNotEqualTo(Integer value) {
            addCriterion("map_id <>", value, "mapId");
            return (Criteria) this;
        }

        public Criteria andMapIdGreaterThan(Integer value) {
            addCriterion("map_id >", value, "mapId");
            return (Criteria) this;
        }

        public Criteria andMapIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("map_id >=", value, "mapId");
            return (Criteria) this;
        }

        public Criteria andMapIdLessThan(Integer value) {
            addCriterion("map_id <", value, "mapId");
            return (Criteria) this;
        }

        public Criteria andMapIdLessThanOrEqualTo(Integer value) {
            addCriterion("map_id <=", value, "mapId");
            return (Criteria) this;
        }

        public Criteria andMapIdIn(List<Integer> values) {
            addCriterion("map_id in", values, "mapId");
            return (Criteria) this;
        }

        public Criteria andMapIdNotIn(List<Integer> values) {
            addCriterion("map_id not in", values, "mapId");
            return (Criteria) this;
        }

        public Criteria andMapIdBetween(Integer value1, Integer value2) {
            addCriterion("map_id between", value1, value2, "mapId");
            return (Criteria) this;
        }

        public Criteria andMapIdNotBetween(Integer value1, Integer value2) {
            addCriterion("map_id not between", value1, value2, "mapId");
            return (Criteria) this;
        }

        public Criteria andPoiNameIsNull() {
            addCriterion("poi_name is null");
            return (Criteria) this;
        }

        public Criteria andPoiNameIsNotNull() {
            addCriterion("poi_name is not null");
            return (Criteria) this;
        }

        public Criteria andPoiNameEqualTo(String value) {
            addCriterion("poi_name =", value, "poiName");
            return (Criteria) this;
        }

        public Criteria andPoiNameNotEqualTo(String value) {
            addCriterion("poi_name <>", value, "poiName");
            return (Criteria) this;
        }

        public Criteria andPoiNameGreaterThan(String value) {
            addCriterion("poi_name >", value, "poiName");
            return (Criteria) this;
        }

        public Criteria andPoiNameGreaterThanOrEqualTo(String value) {
            addCriterion("poi_name >=", value, "poiName");
            return (Criteria) this;
        }

        public Criteria andPoiNameLessThan(String value) {
            addCriterion("poi_name <", value, "poiName");
            return (Criteria) this;
        }

        public Criteria andPoiNameLessThanOrEqualTo(String value) {
            addCriterion("poi_name <=", value, "poiName");
            return (Criteria) this;
        }

        public Criteria andPoiNameLike(String value) {
            addCriterion("poi_name like", value, "poiName");
            return (Criteria) this;
        }

        public Criteria andPoiNameNotLike(String value) {
            addCriterion("poi_name not like", value, "poiName");
            return (Criteria) this;
        }

        public Criteria andPoiNameIn(List<String> values) {
            addCriterion("poi_name in", values, "poiName");
            return (Criteria) this;
        }

        public Criteria andPoiNameNotIn(List<String> values) {
            addCriterion("poi_name not in", values, "poiName");
            return (Criteria) this;
        }

        public Criteria andPoiNameBetween(String value1, String value2) {
            addCriterion("poi_name between", value1, value2, "poiName");
            return (Criteria) this;
        }

        public Criteria andPoiNameNotBetween(String value1, String value2) {
            addCriterion("poi_name not between", value1, value2, "poiName");
            return (Criteria) this;
        }

        public Criteria andPoiVertexIsNull() {
            addCriterion("poi_vertex is null");
            return (Criteria) this;
        }

        public Criteria andPoiVertexIsNotNull() {
            addCriterion("poi_vertex is not null");
            return (Criteria) this;
        }

        public Criteria andPoiVertexEqualTo(String value) {
            addCriterion("poi_vertex =", value, "poiVertex");
            return (Criteria) this;
        }

        public Criteria andPoiVertexNotEqualTo(String value) {
            addCriterion("poi_vertex <>", value, "poiVertex");
            return (Criteria) this;
        }

        public Criteria andPoiVertexGreaterThan(String value) {
            addCriterion("poi_vertex >", value, "poiVertex");
            return (Criteria) this;
        }

        public Criteria andPoiVertexGreaterThanOrEqualTo(String value) {
            addCriterion("poi_vertex >=", value, "poiVertex");
            return (Criteria) this;
        }

        public Criteria andPoiVertexLessThan(String value) {
            addCriterion("poi_vertex <", value, "poiVertex");
            return (Criteria) this;
        }

        public Criteria andPoiVertexLessThanOrEqualTo(String value) {
            addCriterion("poi_vertex <=", value, "poiVertex");
            return (Criteria) this;
        }

        public Criteria andPoiVertexLike(String value) {
            addCriterion("poi_vertex like", value, "poiVertex");
            return (Criteria) this;
        }

        public Criteria andPoiVertexNotLike(String value) {
            addCriterion("poi_vertex not like", value, "poiVertex");
            return (Criteria) this;
        }

        public Criteria andPoiVertexIn(List<String> values) {
            addCriterion("poi_vertex in", values, "poiVertex");
            return (Criteria) this;
        }

        public Criteria andPoiVertexNotIn(List<String> values) {
            addCriterion("poi_vertex not in", values, "poiVertex");
            return (Criteria) this;
        }

        public Criteria andPoiVertexBetween(String value1, String value2) {
            addCriterion("poi_vertex between", value1, value2, "poiVertex");
            return (Criteria) this;
        }

        public Criteria andPoiVertexNotBetween(String value1, String value2) {
            addCriterion("poi_vertex not between", value1, value2, "poiVertex");
            return (Criteria) this;
        }

        public Criteria andPoiCenterIsNull() {
            addCriterion("poi_center is null");
            return (Criteria) this;
        }

        public Criteria andPoiCenterIsNotNull() {
            addCriterion("poi_center is not null");
            return (Criteria) this;
        }

        public Criteria andPoiCenterEqualTo(String value) {
            addCriterion("poi_center =", value, "poiCenter");
            return (Criteria) this;
        }

        public Criteria andPoiCenterNotEqualTo(String value) {
            addCriterion("poi_center <>", value, "poiCenter");
            return (Criteria) this;
        }

        public Criteria andPoiCenterGreaterThan(String value) {
            addCriterion("poi_center >", value, "poiCenter");
            return (Criteria) this;
        }

        public Criteria andPoiCenterGreaterThanOrEqualTo(String value) {
            addCriterion("poi_center >=", value, "poiCenter");
            return (Criteria) this;
        }

        public Criteria andPoiCenterLessThan(String value) {
            addCriterion("poi_center <", value, "poiCenter");
            return (Criteria) this;
        }

        public Criteria andPoiCenterLessThanOrEqualTo(String value) {
            addCriterion("poi_center <=", value, "poiCenter");
            return (Criteria) this;
        }

        public Criteria andPoiCenterLike(String value) {
            addCriterion("poi_center like", value, "poiCenter");
            return (Criteria) this;
        }

        public Criteria andPoiCenterNotLike(String value) {
            addCriterion("poi_center not like", value, "poiCenter");
            return (Criteria) this;
        }

        public Criteria andPoiCenterIn(List<String> values) {
            addCriterion("poi_center in", values, "poiCenter");
            return (Criteria) this;
        }

        public Criteria andPoiCenterNotIn(List<String> values) {
            addCriterion("poi_center not in", values, "poiCenter");
            return (Criteria) this;
        }

        public Criteria andPoiCenterBetween(String value1, String value2) {
            addCriterion("poi_center between", value1, value2, "poiCenter");
            return (Criteria) this;
        }

        public Criteria andPoiCenterNotBetween(String value1, String value2) {
            addCriterion("poi_center not between", value1, value2, "poiCenter");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table poi
     *
     * @mbggenerated do_not_delete_during_merge Wed Apr 10 10:47:33 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table poi
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}