package com.bluefireplatform.mapper;

import com.bluefireplatform.entity.IndoorPresentLocation;
import com.bluefireplatform.entity.IndoorPresentLocationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IndoorPresentLocationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indoor_present_location
     *
     * @mbggenerated Thu May 09 09:23:18 CST 2019
     */
    int countByExample(IndoorPresentLocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indoor_present_location
     *
     * @mbggenerated Thu May 09 09:23:18 CST 2019
     */
    int deleteByExample(IndoorPresentLocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indoor_present_location
     *
     * @mbggenerated Thu May 09 09:23:18 CST 2019
     */
    int deleteByPrimaryKey(Integer locationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indoor_present_location
     *
     * @mbggenerated Thu May 09 09:23:18 CST 2019
     */
    int insert(IndoorPresentLocation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indoor_present_location
     *
     * @mbggenerated Thu May 09 09:23:18 CST 2019
     */
    int insertSelective(IndoorPresentLocation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indoor_present_location
     *
     * @mbggenerated Thu May 09 09:23:18 CST 2019
     */
    List<IndoorPresentLocation> selectByExample(IndoorPresentLocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indoor_present_location
     *
     * @mbggenerated Thu May 09 09:23:18 CST 2019
     */
    IndoorPresentLocation selectByPrimaryKey(Integer locationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indoor_present_location
     *
     * @mbggenerated Thu May 09 09:23:18 CST 2019
     */
    int updateByExampleSelective(@Param("record") IndoorPresentLocation record, @Param("example") IndoorPresentLocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indoor_present_location
     *
     * @mbggenerated Thu May 09 09:23:18 CST 2019
     */
    int updateByExample(@Param("record") IndoorPresentLocation record, @Param("example") IndoorPresentLocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indoor_present_location
     *
     * @mbggenerated Thu May 09 09:23:18 CST 2019
     */
    int updateByPrimaryKeySelective(IndoorPresentLocation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indoor_present_location
     *
     * @mbggenerated Thu May 09 09:23:18 CST 2019
     */
    int updateByPrimaryKey(IndoorPresentLocation record);
}