package com.bluefireplatform.mapper;

import com.bluefireplatform.entity.IndoorMiddleTab;
import com.bluefireplatform.entity.IndoorMiddleTabExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IndoorMiddleTabMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indoor_middle_tab
     *
     * @mbggenerated Tue Apr 16 14:59:31 CST 2019
     */
    int countByExample(IndoorMiddleTabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indoor_middle_tab
     *
     * @mbggenerated Tue Apr 16 14:59:31 CST 2019
     */
    int deleteByExample(IndoorMiddleTabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indoor_middle_tab
     *
     * @mbggenerated Tue Apr 16 14:59:31 CST 2019
     */
    int deleteByPrimaryKey(Integer indoorMiddleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indoor_middle_tab
     *
     * @mbggenerated Tue Apr 16 14:59:31 CST 2019
     */
    int insert(IndoorMiddleTab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indoor_middle_tab
     *
     * @mbggenerated Tue Apr 16 14:59:31 CST 2019
     */
    int insertSelective(IndoorMiddleTab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indoor_middle_tab
     *
     * @mbggenerated Tue Apr 16 14:59:31 CST 2019
     */
    List<IndoorMiddleTab> selectByExample(IndoorMiddleTabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indoor_middle_tab
     *
     * @mbggenerated Tue Apr 16 14:59:31 CST 2019
     */
    IndoorMiddleTab selectByPrimaryKey(Integer indoorMiddleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indoor_middle_tab
     *
     * @mbggenerated Tue Apr 16 14:59:31 CST 2019
     */
    int updateByExampleSelective(@Param("record") IndoorMiddleTab record, @Param("example") IndoorMiddleTabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indoor_middle_tab
     *
     * @mbggenerated Tue Apr 16 14:59:31 CST 2019
     */
    int updateByExample(@Param("record") IndoorMiddleTab record, @Param("example") IndoorMiddleTabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indoor_middle_tab
     *
     * @mbggenerated Tue Apr 16 14:59:31 CST 2019
     */
    int updateByPrimaryKeySelective(IndoorMiddleTab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indoor_middle_tab
     *
     * @mbggenerated Tue Apr 16 14:59:31 CST 2019
     */
    int updateByPrimaryKey(IndoorMiddleTab record);
}