package com.bluefireplatform.mapper;

import com.bluefireplatform.entity.IndoorMapmatching;
import com.bluefireplatform.entity.IndoorMapmatchingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IndoorMapmatchingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indoor_mapmatching
     *
     * @mbggenerated Mon Apr 29 11:09:34 CST 2019
     */
    int countByExample(IndoorMapmatchingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indoor_mapmatching
     *
     * @mbggenerated Mon Apr 29 11:09:34 CST 2019
     */
    int deleteByExample(IndoorMapmatchingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indoor_mapmatching
     *
     * @mbggenerated Mon Apr 29 11:09:34 CST 2019
     */
    int deleteByPrimaryKey(Integer trajectoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indoor_mapmatching
     *
     * @mbggenerated Mon Apr 29 11:09:34 CST 2019
     */
    int insert(IndoorMapmatching record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indoor_mapmatching
     *
     * @mbggenerated Mon Apr 29 11:09:34 CST 2019
     */
    int insertSelective(IndoorMapmatching record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indoor_mapmatching
     *
     * @mbggenerated Mon Apr 29 11:09:34 CST 2019
     */
    List<IndoorMapmatching> selectByExample(IndoorMapmatchingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indoor_mapmatching
     *
     * @mbggenerated Mon Apr 29 11:09:34 CST 2019
     */
    IndoorMapmatching selectByPrimaryKey(Integer trajectoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indoor_mapmatching
     *
     * @mbggenerated Mon Apr 29 11:09:34 CST 2019
     */
    int updateByExampleSelective(@Param("record") IndoorMapmatching record, @Param("example") IndoorMapmatchingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indoor_mapmatching
     *
     * @mbggenerated Mon Apr 29 11:09:34 CST 2019
     */
    int updateByExample(@Param("record") IndoorMapmatching record, @Param("example") IndoorMapmatchingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indoor_mapmatching
     *
     * @mbggenerated Mon Apr 29 11:09:34 CST 2019
     */
    int updateByPrimaryKeySelective(IndoorMapmatching record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indoor_mapmatching
     *
     * @mbggenerated Mon Apr 29 11:09:34 CST 2019
     */
    int updateByPrimaryKey(IndoorMapmatching record);
}