package com.bluefireplatform.mapper;

import com.bluefireplatform.entity.Map;
import com.bluefireplatform.entity.MapExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MapMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    int countByExample(MapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    int deleteByExample(MapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    int deleteByPrimaryKey(Integer mapId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    int insert(Map record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    int insertSelective(Map record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    List<Map> selectByExample(MapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    Map selectByPrimaryKey(Integer mapId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    int updateByExampleSelective(@Param("record") Map record, @Param("example") MapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    int updateByExample(@Param("record") Map record, @Param("example") MapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    int updateByPrimaryKeySelective(Map record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    int updateByPrimaryKey(Map record);
}