package com.bluefireplatform.mapper;

import com.bluefireplatform.entity.OutdoorMapmatching;
import com.bluefireplatform.entity.OutdoorMapmatchingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OutdoorMapmatchingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outdoor_mapmatching
     *
     * @mbggenerated Fri Apr 26 17:21:08 CST 2019
     */
    int countByExample(OutdoorMapmatchingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outdoor_mapmatching
     *
     * @mbggenerated Fri Apr 26 17:21:08 CST 2019
     */
    int deleteByExample(OutdoorMapmatchingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outdoor_mapmatching
     *
     * @mbggenerated Fri Apr 26 17:21:08 CST 2019
     */
    int deleteByPrimaryKey(Integer trajectoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outdoor_mapmatching
     *
     * @mbggenerated Fri Apr 26 17:21:08 CST 2019
     */
    int insert(OutdoorMapmatching record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outdoor_mapmatching
     *
     * @mbggenerated Fri Apr 26 17:21:08 CST 2019
     */
    int insertSelective(OutdoorMapmatching record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outdoor_mapmatching
     *
     * @mbggenerated Fri Apr 26 17:21:08 CST 2019
     */
    List<OutdoorMapmatching> selectByExample(OutdoorMapmatchingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outdoor_mapmatching
     *
     * @mbggenerated Fri Apr 26 17:21:08 CST 2019
     */
    OutdoorMapmatching selectByPrimaryKey(Integer trajectoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outdoor_mapmatching
     *
     * @mbggenerated Fri Apr 26 17:21:08 CST 2019
     */
    int updateByExampleSelective(@Param("record") OutdoorMapmatching record, @Param("example") OutdoorMapmatchingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outdoor_mapmatching
     *
     * @mbggenerated Fri Apr 26 17:21:08 CST 2019
     */
    int updateByExample(@Param("record") OutdoorMapmatching record, @Param("example") OutdoorMapmatchingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outdoor_mapmatching
     *
     * @mbggenerated Fri Apr 26 17:21:08 CST 2019
     */
    int updateByPrimaryKeySelective(OutdoorMapmatching record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outdoor_mapmatching
     *
     * @mbggenerated Fri Apr 26 17:21:08 CST 2019
     */
    int updateByPrimaryKey(OutdoorMapmatching record);
}