package com.bluefireplatform.mapper;

import com.bluefireplatform.entity.OutdoorMiddleTab;
import com.bluefireplatform.entity.OutdoorMiddleTabExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OutdoorMiddleTabMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outdoor_middle_tab
     *
     * @mbggenerated Mon Apr 22 14:24:57 CST 2019
     */
    int countByExample(OutdoorMiddleTabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outdoor_middle_tab
     *
     * @mbggenerated Mon Apr 22 14:24:57 CST 2019
     */
    int deleteByExample(OutdoorMiddleTabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outdoor_middle_tab
     *
     * @mbggenerated Mon Apr 22 14:24:57 CST 2019
     */
    int deleteByPrimaryKey(Integer outdoorMiddleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outdoor_middle_tab
     *
     * @mbggenerated Mon Apr 22 14:24:57 CST 2019
     */
    int insert(OutdoorMiddleTab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outdoor_middle_tab
     *
     * @mbggenerated Mon Apr 22 14:24:57 CST 2019
     */
    int insertSelective(OutdoorMiddleTab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outdoor_middle_tab
     *
     * @mbggenerated Mon Apr 22 14:24:57 CST 2019
     */
    List<OutdoorMiddleTab> selectByExample(OutdoorMiddleTabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outdoor_middle_tab
     *
     * @mbggenerated Mon Apr 22 14:24:57 CST 2019
     */
    OutdoorMiddleTab selectByPrimaryKey(Integer outdoorMiddleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outdoor_middle_tab
     *
     * @mbggenerated Mon Apr 22 14:24:57 CST 2019
     */
    int updateByExampleSelective(@Param("record") OutdoorMiddleTab record, @Param("example") OutdoorMiddleTabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outdoor_middle_tab
     *
     * @mbggenerated Mon Apr 22 14:24:57 CST 2019
     */
    int updateByExample(@Param("record") OutdoorMiddleTab record, @Param("example") OutdoorMiddleTabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outdoor_middle_tab
     *
     * @mbggenerated Mon Apr 22 14:24:57 CST 2019
     */
    int updateByPrimaryKeySelective(OutdoorMiddleTab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outdoor_middle_tab
     *
     * @mbggenerated Mon Apr 22 14:24:57 CST 2019
     */
    int updateByPrimaryKey(OutdoorMiddleTab record);
}