package com.bluefireplatform.mapper;

import com.bluefireplatform.entity.OutdoorCompression;
import com.bluefireplatform.entity.OutdoorCompressionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OutdoorCompressionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outdoor_compression
     *
     * @mbggenerated Fri Apr 26 17:21:08 CST 2019
     */
    int countByExample(OutdoorCompressionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outdoor_compression
     *
     * @mbggenerated Fri Apr 26 17:21:08 CST 2019
     */
    int deleteByExample(OutdoorCompressionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outdoor_compression
     *
     * @mbggenerated Fri Apr 26 17:21:08 CST 2019
     */
    int deleteByPrimaryKey(Integer trajectoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outdoor_compression
     *
     * @mbggenerated Fri Apr 26 17:21:08 CST 2019
     */
    int insert(OutdoorCompression record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outdoor_compression
     *
     * @mbggenerated Fri Apr 26 17:21:08 CST 2019
     */
    int insertSelective(OutdoorCompression record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outdoor_compression
     *
     * @mbggenerated Fri Apr 26 17:21:08 CST 2019
     */
    List<OutdoorCompression> selectByExample(OutdoorCompressionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outdoor_compression
     *
     * @mbggenerated Fri Apr 26 17:21:08 CST 2019
     */
    OutdoorCompression selectByPrimaryKey(Integer trajectoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outdoor_compression
     *
     * @mbggenerated Fri Apr 26 17:21:08 CST 2019
     */
    int updateByExampleSelective(@Param("record") OutdoorCompression record, @Param("example") OutdoorCompressionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outdoor_compression
     *
     * @mbggenerated Fri Apr 26 17:21:08 CST 2019
     */
    int updateByExample(@Param("record") OutdoorCompression record, @Param("example") OutdoorCompressionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outdoor_compression
     *
     * @mbggenerated Fri Apr 26 17:21:08 CST 2019
     */
    int updateByPrimaryKeySelective(OutdoorCompression record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outdoor_compression
     *
     * @mbggenerated Fri Apr 26 17:21:08 CST 2019
     */
    int updateByPrimaryKey(OutdoorCompression record);
}