package com.bluefireplatform.mapper;

import com.bluefireplatform.entity.OutdoorTrajectory;
import com.bluefireplatform.entity.OutdoorTrajectoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OutdoorTrajectoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outdoor_trajectory
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    int countByExample(OutdoorTrajectoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outdoor_trajectory
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    int deleteByExample(OutdoorTrajectoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outdoor_trajectory
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    int deleteByPrimaryKey(Integer outPointId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outdoor_trajectory
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    int insert(OutdoorTrajectory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outdoor_trajectory
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    int insertSelective(OutdoorTrajectory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outdoor_trajectory
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    List<OutdoorTrajectory> selectByExample(OutdoorTrajectoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outdoor_trajectory
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    OutdoorTrajectory selectByPrimaryKey(Integer outPointId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outdoor_trajectory
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    int updateByExampleSelective(@Param("record") OutdoorTrajectory record, @Param("example") OutdoorTrajectoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outdoor_trajectory
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    int updateByExample(@Param("record") OutdoorTrajectory record, @Param("example") OutdoorTrajectoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outdoor_trajectory
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    int updateByPrimaryKeySelective(OutdoorTrajectory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outdoor_trajectory
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    int updateByPrimaryKey(OutdoorTrajectory record);
}