package com.bluefireplatform.mapper;

import com.bluefireplatform.entity.Poi;
import com.bluefireplatform.entity.PoiExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PoiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poi
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    int countByExample(PoiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poi
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    int deleteByExample(PoiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poi
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    int deleteByPrimaryKey(Integer poiId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poi
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    int insert(Poi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poi
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    int insertSelective(Poi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poi
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    List<Poi> selectByExample(PoiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poi
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    Poi selectByPrimaryKey(Integer poiId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poi
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    int updateByExampleSelective(@Param("record") Poi record, @Param("example") PoiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poi
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    int updateByExample(@Param("record") Poi record, @Param("example") PoiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poi
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    int updateByPrimaryKeySelective(Poi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poi
     *
     * @mbggenerated Wed Apr 10 10:47:33 CST 2019
     */
    int updateByPrimaryKey(Poi record);
}